# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'iOSProjectStarter' do
  use_frameworks!

  # Pods for iOSProjectStarter
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'iOSProjectStarterSpec' do
  use_frameworks!
  testing_pods  
end
